// src/components/login/LoginSettingsModal.vue
<template>
  <Teleport to="body">
    <div v-if="modelValue" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60">
      <div class="absolute inset-0" @click="close"></div>
      <div class="login-settings-dialog relative bg-white w-full p-8 shadow-2xl z-10 animate-fade-in-up">
        <button @click="close" class="absolute top-6 right-6 text-slate-800 hover:bg-slate-100 p-2 rounded-full transition-colors">
          <CloseIcon :size="28" />
        </button>

        <h2 class="text-[26px] font-semibold text-slate-900 mb-8 mt-2 tracking-tight">Usuń profile z tej przeglądarki</h2>

        <div class="flex items-center justify-between border border-slate-200 rounded-xl p-4 mb-6">
          <div class="flex items-center gap-4">
            <div class="login-settings-avatar rounded-full overflow-hidden border border-slate-100">
              <img :src="userProfile.avatar" :alt="userProfile.name" class="w-full h-full object-cover" />
            </div>
            <div class="flex flex-col text-left">
              <span class="text-[17px] font-medium text-slate-900">{{ userProfile.name }}</span>
              <span class="text-[15px] text-slate-500">Facebook</span>
            </div>
          </div>
          <button class="px-6 py-2 border border-slate-300 rounded-full font-medium text-slate-900 bg-white hover:bg-slate-50 transition-colors text-[15px]">Usuń</button>
        </div>

          <p class="text-[15px] text-slate-500 text-left">
          <a href="#" class="text-primary font-semibold hover:underline">Dowiedz się więcej</a>
          na temat tego, dlaczego widzisz tutaj profile i co oznacza ich usunięcie.
        </p>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import CloseIcon from 'vue-material-design-icons/Close.vue';

interface UserProfile {
  name: string;
  avatar: string;
}

defineProps<{
  modelValue: boolean;
  userProfile: UserProfile;
}>();

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void;
}>();

const close = () => emit('update:modelValue', false);
</script>

<style scoped>
@keyframes fade-in-up {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}
.animate-fade-in-up { animation: fade-in-up 0.2s ease-out forwards; }

.login-settings-dialog {
  max-width: 550px;
  border-radius: 24px;
}

.login-settings-avatar {
  width: 50px;
  height: 50px;
}
</style>

// keycloak/themes/src/components/LoginSettingsModal.tsx
import React from 'react'
import { createPortal } from 'react-dom'
import { X } from 'lucide-react'

interface UserProfile {
  id: number
  name: string
  avatar: string
}

interface LoginSettingsModalProps {
  isOpen: boolean
  onClose: () => void
  profiles: UserProfile[]
  onRemoveProfile?: (id: number) => void
}

export const LoginSettingsModal: React.FC<LoginSettingsModalProps> = ({
  isOpen,
  onClose,
  profiles,
  onRemoveProfile
}) => {
  if (!isOpen) return null

  const handleRemove = (id: number) => {
    onRemoveProfile?.(id)
  }

  return createPortal(
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60">
      <div
        className="absolute inset-0"
        onClick={onClose}
      />
      <div className="relative bg-white w-full max-w-[550px] rounded-[24px] p-8 shadow-2xl z-10 animate-fade-in-up">
        <button
          className="absolute top-6 right-6 text-slate-800 hover:bg-slate-100 p-2 rounded-full transition-colors cursor-pointer"
          onClick={onClose}
        >
          <X size={28} />
        </button>

        <h2 className="text-[26px] font-semibold text-slate-900 mb-8 mt-2 tracking-tight">
          Usuń profile z tej przeglądarki
        </h2>

        {profiles.map((profile) => (
          <div
            key={profile.id}
            className="flex items-center justify-between border border-slate-200 rounded-xl p-4 mb-6"
          >
            <div className="flex items-center gap-4">
              <div className="w-[50px] h-[50px] rounded-full overflow-hidden border border-slate-100">
                <img
                  src={profile.avatar}
                  alt={profile.name}
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="flex flex-col text-left">
                <span className="text-[17px] font-medium text-slate-900">{profile.name}</span>
                <span className="text-[15px] text-slate-500">Facebook</span>
              </div>
            </div>
            <button
              onClick={() => handleRemove(profile.id)}
              className="px-6 py-2 border border-slate-300 rounded-full font-medium text-slate-900 bg-white hover:bg-slate-50 transition-colors text-[15px] cursor-pointer"
            >
              Usuń
            </button>
          </div>
        ))}

        <p className="text-[15px] text-slate-500 text-left">
          <a
            href="#"
            className="text-primary font-semibold hover:underline"
          >Dowiedz się więcej</a>
          {" "}na temat tego, dlaczego widzisz tutaj profile i co oznacza ich usunięcie.
        </p>
      </div>
    </div>,
    document.body
  )
}

export default LoginSettingsModal
